### ISSUE TITLE
Event based

### ISSUE THREAD

**Issue by msj121** [ngokevin/aframe-animation-component#2]
Very interesting new approach.

2 questions:

1). Is this the new plan for future animations in the core, or just an alternative? (too early?)
2). Will event based animations be possible? Didnt notice anything in the code.

Thanks

**Comment by ngokevin** [comment]
1) Don't know. At the very least, I would like the `<a-animation>` to deprecate. And I guess I might like this to be standard, but we'll see.
2) Yeah, I will add that soon.
