### ISSUE TITLE
How to use events?

### ISSUE THREAD

**Issue by BSVogler** [ngokevin/aframe-animation-component#7]
I tried using the DOM event listener

```html
<a-entity id="cursor" geometry="primitive: box;width:0.5;height:0.5;depth:0.5;" animation="property: position; from:0 0 0;to: 1 1 1;dur:3000;"></a-entity>
```

```javascript
document.getElementById("cursor").addEventListener("animationbegin", function(){ alert("Hello World!"); });
```

using the events`animationbegin`, but the event does not fire. The animation does work though. Is this a bug or should the events used in a different way? Could not found much information on the events in the A-Frame docs or this one.

**Comment by masterofshapes** [comment]
Have same question were you able to resolve?

**Comment by masterofshapes** [comment]
Have same question were you able to resolve @BSVogler

**Comment by BSVogler** [comment]
@masterofshapes I'm really confused what my intention in this post was. I'm completely out of the loop. I looked it up and saw steht I did not use the animation component in the end. I applied the animation like this

```javascript
var anim = document.createElement("a-animation");
anim.setAttribute("attribute", "rotation");
anim.setAttribute("from", (euler1.x * 180 / Math.PI) + " " + (euler1.y * 180 / Math.PI) + " "+ (euler1.z * 180 / Math.PI));
anim.setAttribute("to", (euler2.x * 180 / Math.PI) + " " + (euler2.y * 180 / Math.PI) + " "+ (euler2.z * 180 / Math.PI));
anim.setAttribute("dur", dur);
cursorNode.appendChild(anim);```

Source Code:
https://github.com/BSVogler/MovementPathVisualizer

**Comment by masterofshapes** [comment]
Sorry @BSVogler I should of clarified. Were you ever able to successfully get the "animationcomplete" or "animationbegin" events to work using https://github.com/ngokevin/aframe-animation-component

**Comment by BSVogler** [comment]
`Animationen`: `document.getElementById("cursor").addEventListener("animationend", nextAnimationStep);`

**Comment by ngokevin** [comment]
Here's an example with this component (which has been moved to kframe): 

https://github.com/ngokevin/kframe/tree/master/components/animation/examples/events/


https://ngokevin.github.io/kframe/components/animation/examples/events/

**Comment by masterofshapes** [comment]
@ngokevin thanks but my question was specific to the animationbegin and animation complete events. I understand how to use the events on the animation component itself. But When I add an event listener for the animationcomplete event on my element I never get it to trigger.  I'm trying to call a function only after an animation has finished completely and I'm trying to avoid using a bunch of setTImeouts. In your example it didn't appear to have adding an event listener for those events (unless I missed it) 

Thanks

**Comment by ngokevin** [comment]
Oops, docs were off. The events had a hyphen https://github.com/ngokevin/kframe/blob/master/components/animation/index.js#L57

I am going to remove the hyphen and bump it. Find it at https://github.com/ngokevin/kframe/tree/master/components/animation
